const obj = {
  result: true,
  data: [
    {
      roomId: "28999K",
      roomName: "Double",
      hotelMarkup: 0.3,
      availabilities: 15,
      ratePackages: [
        {
          ratePlanId: "7XFISR",
          ratePlanName: "Double 1",
          adultGuestsIncluded: 2,
          childGuestsIncluded: 0,
          maxGuests: 2,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 150,
          amount: 150,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          minNights: 1,
          maxNights: 10,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ADULT_CHILD",
          fromDate: "2022-08-31",
          toDate: "2022-08-31",
        },
        {
          ratePlanId: "7XFISR",
          ratePlanName: "Double 1",
          adultGuestsIncluded: 2,
          childGuestsIncluded: 0,
          maxGuests: 2,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 150,
          amount: 150,
          promotions: [],
          currency: "USD",
          stopSell: 1,
          minNights: 1,
          maxNights: 10,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ADULT_CHILD",
          fromDate: "2022-09-01",
          toDate: "2022-09-30",
        },
        {
          ratePlanId: "7XFISR",
          ratePlanName: "Double 1",
          adultGuestsIncluded: 2,
          childGuestsIncluded: 0,
          maxGuests: 2,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 150,
          amount: 150,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          minNights: 1,
          maxNights: 10,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ADULT_CHILD",
          fromDate: "2022-10-01",
          toDate: "2023-01-31",
        },
        {
          ratePlanId: "7XFISR",
          ratePlanName: "Double 1",
          adultGuestsIncluded: 2,
          childGuestsIncluded: 0,
          maxGuests: 2,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 110,
          amount: 110,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          minNights: 1,
          maxNights: 10,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ADULT_CHILD",
          fromDate: "2023-02-01",
          toDate: "2023-02-01",
        },
        {
          ratePlanId: "7XFISR",
          ratePlanName: "Double 1",
          adultGuestsIncluded: 2,
          childGuestsIncluded: 0,
          maxGuests: 2,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 150,
          amount: 150,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          minNights: 1,
          maxNights: 10,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ADULT_CHILD",
          fromDate: "2023-02-02",
          toDate: "2023-11-27",
        },
        {
          ratePlanId: "7XFISR",
          ratePlanName: "Double 1",
          adultGuestsIncluded: 2,
          childGuestsIncluded: 0,
          maxGuests: 2,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 150,
          amount: 150,
          promotions: [],
          currency: "USD",
          minNights: 1,
          maxNights: 10,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ADULT_CHILD",
          fromDate: "2023-11-28",
          toDate: "2023-11-28",
        },
        {
          ratePlanId: "7XFISR",
          ratePlanName: "Double 1",
          adultGuestsIncluded: 2,
          childGuestsIncluded: 0,
          maxGuests: 2,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 150,
          amount: 150,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          minNights: 1,
          maxNights: 10,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ADULT_CHILD",
          fromDate: "2023-11-29",
          toDate: "2023-12-07",
        },
        {
          ratePlanId: "7XFISR",
          ratePlanName: "Double 1",
          adultGuestsIncluded: 2,
          childGuestsIncluded: 0,
          maxGuests: 2,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 150,
          amount: 150,
          promotions: [],
          currency: "USD",
          minNights: 1,
          maxNights: 10,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ADULT_CHILD",
          fromDate: "2023-12-08",
          toDate: "2023-12-31",
        },
        {
          ratePlanId: "7XFISR",
          ratePlanName: "Double 1",
          adultGuestsIncluded: 2,
          childGuestsIncluded: 0,
          maxGuests: 2,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 150,
          amount: 150,
          promotions: [],
          currency: "USD",
          minNights: 2,
          maxNights: 10,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ADULT_CHILD",
          fromDate: "2024-01-01",
          toDate: "2024-03-31",
        },
        {
          ratePlanId: "7XFISR",
          ratePlanName: "Double 1",
          adultGuestsIncluded: 2,
          childGuestsIncluded: 0,
          maxGuests: 2,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 150,
          amount: 150,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          minNights: 2,
          maxNights: 10,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ADULT_CHILD",
          fromDate: "2024-04-01",
          toDate: "2024-04-30",
        },
        {
          ratePlanId: "7XFISR",
          ratePlanName: "Double 1",
          adultGuestsIncluded: 2,
          childGuestsIncluded: 0,
          maxGuests: 2,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 150,
          amount: 150,
          promotions: [],
          currency: "USD",
          minNights: 2,
          maxNights: 10,
          closeToArrival: 1,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ADULT_CHILD",
          fromDate: "2024-05-01",
          toDate: "2024-05-31",
        },
        {
          ratePlanId: "7XFISR",
          ratePlanName: "Double 1",
          adultGuestsIncluded: 2,
          childGuestsIncluded: 0,
          maxGuests: 2,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 150,
          amount: 150,
          promotions: [],
          currency: "USD",
          minNights: 2,
          maxNights: 10,
          closeToArrival: 0,
          closeToDeparture: 1,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ADULT_CHILD",
          fromDate: "2024-06-01",
          toDate: "2024-06-30",
        },
      ],
    },
    {
      roomId: "LSMS1X",
      roomName: "Single",
      hotelMarkup: 0.3,
      availabilities: 5,
      ratePackages: [
        {
          ratePlanId: "YA24ST",
          ratePlanName: "Single 1",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 4,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2022-08-31",
          toDate: "2022-08-31",
        },
        {
          ratePlanId: "YA24ST",
          ratePlanName: "Single 1",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 4,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          closeToArrival: 0,
          closeToDeparture: 1,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2022-09-01",
          toDate: "2022-09-15",
        },
        {
          ratePlanId: "YA24ST",
          ratePlanName: "Single 1",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 4,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2022-09-16",
          toDate: "2022-09-30",
        },
        {
          ratePlanId: "YA24ST",
          ratePlanName: "Single 1",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 4,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          closeToArrival: 1,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2022-10-01",
          toDate: "2022-10-15",
        },
        {
          ratePlanId: "YA24ST",
          ratePlanName: "Single 1",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 4,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2022-10-16",
          toDate: "2022-10-31",
        },
        {
          ratePlanId: "YA24ST",
          ratePlanName: "Single 1",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 4,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          minNights: 2,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2022-11-01",
          toDate: "2022-11-30",
        },
        {
          ratePlanId: "YA24ST",
          ratePlanName: "Single 1",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 4,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          maxNights: 5,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2022-12-01",
          toDate: "2022-12-31",
        },
        {
          ratePlanId: "YA24ST",
          ratePlanName: "Single 1",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 4,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2023-01-01",
          toDate: "2023-11-27",
        },
        {
          ratePlanId: "YA24ST",
          ratePlanName: "Single 1",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 4,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2023-11-28",
          toDate: "2023-11-28",
        },
        {
          ratePlanId: "YA24ST",
          ratePlanName: "Single 1",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 4,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2023-11-29",
          toDate: "2023-12-07",
        },
        {
          ratePlanId: "YA24ST",
          ratePlanName: "Single 1",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 4,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2023-12-08",
          toDate: "2024-03-31",
        },
        {
          ratePlanId: "YA24ST",
          ratePlanName: "Single 1",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 4,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 110,
          amount: 110,
          promotions: [],
          currency: "USD",
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2024-04-01",
          toDate: "2024-04-30",
        },
      ],
    },
    {
      roomId: "QMHPDM",
      roomName: "Triple",
      hotelMarkup: 0.3,
      availabilities: 5,
      ratePackages: [
        {
          ratePlanId: "VI8UTC",
          ratePlanName: "Triple",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 3,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 1,
          minNights: 2,
          maxNights: 999,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2022-08-31",
          toDate: "2022-08-31",
        },
        {
          ratePlanId: "VI8UTC",
          ratePlanName: "Triple",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 3,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          minNights: 2,
          maxNights: 999,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2022-09-01",
          toDate: "2023-10-19",
        },
        {
          ratePlanId: "VI8UTC",
          ratePlanName: "Triple",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 3,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          minNights: 2,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2023-10-20",
          toDate: "2023-10-20",
        },
        {
          ratePlanId: "VI8UTC",
          ratePlanName: "Triple",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 3,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          minNights: 2,
          maxNights: 999,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2023-10-21",
          toDate: "2023-10-24",
        },
        {
          ratePlanId: "VI8UTC",
          ratePlanName: "Triple",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 3,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          minNights: 2,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2023-10-25",
          toDate: "2023-11-06",
        },
        {
          ratePlanId: "VI8UTC",
          ratePlanName: "Triple",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 3,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          minNights: 2,
          maxNights: 999,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2023-11-07",
          toDate: "2023-11-27",
        },
        {
          ratePlanId: "VI8UTC",
          ratePlanName: "Triple",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 3,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          minNights: 2,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2023-11-28",
          toDate: "2023-11-28",
        },
        {
          ratePlanId: "VI8UTC",
          ratePlanName: "Triple",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 3,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          stopSell: 0,
          minNights: 2,
          maxNights: 999,
          closeToArrival: 0,
          closeToDeparture: 0,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2023-11-29",
          toDate: "2023-12-07",
        },
        {
          ratePlanId: "VI8UTC",
          ratePlanName: "Triple",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 3,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          minNights: 2,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2023-12-08",
          toDate: "2024-03-30",
        },
        {
          ratePlanId: "VI8UTC",
          ratePlanName: "Triple",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 3,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 100,
          amount: 100,
          promotions: [],
          currency: "USD",
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2024-03-31",
          toDate: "2024-03-31",
        },
        {
          ratePlanId: "VI8UTC",
          ratePlanName: "Triple",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 3,
          freeBreakfast: false,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 0,
          amount: 0,
          promotions: [],
          currency: "USD",
          minNights: 2,
          maxNights: 10,
          inclusions: "NOT_USED",
          extraGuestsConfig: "ONLY_ADULT",
          fromDate: "2024-04-01",
          toDate: "2024-04-30",
        },
        {
          ratePlanId: "Triple_D",
          ratePlanName: "Triple_D",
          adultGuestsIncluded: 1,
          childGuestsIncluded: 0,
          maxGuests: 1,
          freeBreakfast: true,
          freeLunch: false,
          freeDinner: false,
          freeAllInclusive: false,
          roomMarkup: 0.3,
          amountBeforeMarkup: 85,
          amount: 85,
          promotions: [],
          currency: "USD",
          inclusions: "NOT_USED",
          extraGuestsConfig: "ADULT_CHILD",
          fromDate: "2022-08-31",
          toDate: "2024-03-31",
        },
      ],
    },
  ],
  message: "Success",
  error: 0,
};

const roomIds = obj.data.map((item) => {
  const { roomId, roomName } = item;

  return {
    roomId,
    roomName,
    halonghubHotelId: "halonghubHotelId1",
    HotelId: "4c849e7a-1d22-1553657044-40a6-85c8-be15c476c560",
  };
});

console.log(JSON.stringify(roomIds));

const Availabilities = [
  {
    DateRange: { From: "2022-07-28T00:00:00", To: "2022-08-05T00:00:00" },
    Quantity: 12,
    ReleasePeriod: 0,
    Action: "",
  },
  {
    DateRange: { From: "2022-08-06T00:00:00", To: "2022-08-12T00:00:00" },
    Quantity: 100,
    ReleasePeriod: 0,
    Action: "",
  },
];
